# latexindent configuration for pgx-lower-thesis.tex
# Smart paragraph wrapping with word boundary awareness

modifyLineBreaks:
  textWrapOptions:
    columns: 80
    multipleSpacesToSingle: 1
    removeBlockLineBreaks: 0

removeTrailingWhitespace: 1

# Protect environments that shouldn't be wrapped
verbatimEnvironments:
  verbatim: 1
  lstlisting: 1
  minted: 1
  code: 1
